#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER mastok;
	CREATE DATABASE mastok;
	GRANT ALL PRIVILEGES ON DATABASE mastok TO mastok;
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_USER" TO mastok;
EOSQL